export const HEADER = {
  DASHBOARD_DESKTOP_HEIGHT: 72,
};

export const NAVBAR = {
  DASHBOARD_WIDTH: 240,
  DASHBOARD_ITEM_ROOT_HEIGHT: 48,
  DASHBOARD_ITEM_SUB_HEIGHT: 40,
};

export const ICON = {
  NAVBAR_ITEM: 24,
};
